output: mysql-connector.cpp 
	# compile with mysql 
	g++ mysql-connector.cpp -o output -lmysqlcppconn 
	# -L/usr/include/mysql -I/usr/include/mysql -L/home/user/c++/mysqlconnector/include/cppconn -Lmysqlconnector/lib -lmysqlclient -Imysqlconnector/lib/include/cppconn
	# -L/usr/include/mysql -I/usr/include/mysql 
	# -lmysqlcppconn 
	# -L/home/user/c++/mysqlconnector/include/cppconn
	# -Lmysqlconnector/lib -lmysqlclient -Imysqlconnector/lib/include/cppconn

clean:
	rm -f *.o	